config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get "home/about"=>"homes#about",as: :homes

  resources :books
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_up_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @book = Book.new
    @user = current_user
    @books = Book.all
  end

  def show
    @books = Book.new
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @books = Book.new
    @user = current_user
    @users = User.all
  end

  def show
    @books = Book.new
    @user = User.find(params[:id])
    @book = @user.books.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
            <div class="col-md-3">
                <h2>User info</h2>
                <%= attachment_image_tag user, :profile_image, size:'63x63', format: 'jpeg', fallback: "no_image.jpg" %>
                <table class="table">
                    <tbody>
                        <tr></tr>
                        <tr>
                            <th>name</th>
                            <th><%= user.name %></th>
                        </tr>
                        <tr>
                            <th>introduction</th>
                            <th><%= user.introduction %></th>
                        </tr>
                    </tbody>
                </table>
                <div class="row">
                    <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog" do %><% end %>
                </div>

                <h2 class="mt-3">New book</h2>
                <%= form_with model: book, local:true do |f| %>
                  <div class="form-group">
                      <label for="book_title">Title</label>
                      <%= f.text_field :title, class: "form-control book_title text book[title] book_title " %>
                  </div>
                  <div class="form-group">
                      <label for="book_opinion">Opinion</label>
                      <%= f.text_area :body, class: "form-control book_body book[body] book_body" %>
                  </div>
                  <div class="form-group">
                      <%= f.submit 'Create Book', class: "submit commit Create Book btn btn-success Create Book" %>
                  </div>
                <% end %>
            </div>

app/views/books/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

        <h1>Editing Book</h1>

        <div class="text-danger">
          <% if @book.errors.any? %>
            <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>

        <%= form_with model:@book, local: true do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <br><%= f.text_field :title %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <br><%= f.text_area :body %>
          </div>
          <div class ="form-group">
            <input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book" />
          </div>
        <% end %>

        <%= link_to book_path(@book) do %>Show<% end %> |
        <%= link_to books_path do %>Back<% end %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
    <p id="notice"></p>
    <div class="container px-5 px-sm-0">
        <div class="text-danger">
            <% if @book.errors.any? %>
              <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
              <ul>
                  <% @book.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
              </ul>
            <% end %>
        </div>

        <div class="row">
            <%= render 'books/book', book: @book, user: @user %>

            <div class="col-md-8 offset-md-1">
                <h2>Books</h2>
                <table class="table table-hover table-inverse">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Title</th>
                            <th>Opinion</th>
                            <th colspan="3"></th>
                        </tr>
                    </thead>
                    <% @books.each do |book| %>
                      <tbody>
                          <tr>
                              <td>
                                  <%= link_to user_path(book.user.id) do %>
                                    <%= attachment_image_tag book.user, :profile_image, size:'40x40', format: 'jpeg', fallback: "no_image.jpg" %>
                                  <% end %>
                              </td>
                              <td><%= link_to book.title, book_path(book) %></td>
                              <td><%= book.body %></td>
                          </tr>
                      </tbody>
                    <% end %>
                </table>
            </div>
        </div>
    </div>
</main>

app/views/books/show.html.erb
<main>
  <div class="container">
    <div class="row">
      <%= render 'books/book', book: @books, user: @user %>

      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag @user, :profile_image, size:'40x40', format: 'jpeg', fallback: "no_image.jpg" %>
                <br><%= @user.name %>
              <% end %>
            </td>
            <td><%= @book.title %></td>
            <td><%= @book.body %></td>
            <% if @user.id == current_user.id %>
              <td><%= link_to edit_book_path(@book), class: "btn btn-sm btn-success Edit" do %>Edit<% end %></td>
              <td><%= link_to book_path(@book), method: :delete, data: { confirm: '本当に消しますか？'}, class: "btn btn-sm btn-danger Destroy" do %>Destroy<% end %></td>
            <% end %>
          </tr>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(current_user), class: "fas fa-home nav-link text-light" do %>Home<% end %>
                </li>
                <li>
                  <%= link_to users_path, class: "fas fa-users nav-link text-light" do %>Users<% end %>
                </li>
                <li>
                  <%= link_to books_path, class: "fas fa-book-open nav-link text-light" do %>Books<% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" do %>Log out<% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to root_path, class: "fas fa-home nav-link text-light" do %>Home<% end %>
                </li>
                <li>
                  <%= link_to homes_path, class: "fas fa-link nav-link text-light" do %>About<% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: "fas fa-user-plus nav-link text-light" do %>Sign up<% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" do %>Log in<% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <div class="text-success">
      <% if flash[:notice] %>
        <p id="notice">
          <%= flash[:notice] %>
        </p>
      <% end %>
    </div>
    <div class="text-danger">
      <% if flash[:alert] %>
        <p id="notice">
          <%= flash[:alert] %>
        </p>
      <% end %>
    </div>

    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>

        <div class="text-danger">
          <% if @user.errors.any? %>
            <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>

        <%= form_with model:@user, local:true do |f| %>
          <div class="form-group">
            <label for="user_name">Name</label>
            <br><%= f.text_field :name, autofocus: true, id:"user_name" %>
          </div>
          <div class="form-group">
            <label for="user_image">Image</label>
            <br><%= f.attachment_field :profile_image %>
          </div>
          <div class="form-group">
            <label for="user_introduction">Introduction</label>
            <br><%= f.text_field :introduction, autofocus: true, id:"user_introduction" %>
          </div>
          <div class="form-group">
            <input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User" />
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <p id="notice">
    <div class="container px-5 px-sm-0">
      <div class="row">
        <%= render 'books/book', book: @books, user: @user %>

        <div class="col-md-8 offset-md-1">
          <h2>Users</h2>
          <table class="table">
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <% @users.each do |user| %>
              <tbody>
                <tr>
                  <td><%= attachment_image_tag user, :profile_image, size:'40x40', format: 'jpeg', fallback: "no_image.jpg" %></td>
                  <td><%= user.name %></td>
                  <td>
                    <%= link_to user_path(user.id) do %>Show<% end %>
                  </td>
                </tr>
              </tbody>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </p>
</main>

app/views/users/show.html.erb
<main>
  <p id="notice">
    <div class="container px-5 px-sm-0">
      <div class="row">
        <%= render 'books/book', book: @books, user: @user %>

        <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <% @book.each do |book| %>
              <tbody>
                <tr>
                  <td>
                    <%= link_to user_path(book.user.id) do %>
                      <%= attachment_image_tag book.user, :profile_image, size:'40x40', format: 'jpeg', fallback: "no_image.jpg" %>
                    <% end %>
                  </td>
                  <td><%= link_to book.title, book_path(book) %></td>
                  <td><%= book.body %></td>
                </tr>
              </tbody>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </p>
</main>